# Generated by Django 6.0.6 on 2026-06-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorOfCompromise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=255, unique=True)),
                ('ioc_type', models.CharField(choices=[('ip', 'IP Address'), ('domain', 'Domain Name'), ('url', 'URL')], max_length=10)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10)),
                ('total_mentions', models.IntegerField(default=1)),
                ('sources', models.TextField(help_text='Comma-separated names of feeds containing this indicator')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('url', 'Remote URL'), ('file', 'Local File')], default='url', max_length=10)),
                ('location', models.CharField(help_text='Provide the remote HTTP/HTTPS URL', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
