# Generated by Django 6.0.6 on 2026-06-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalystUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_elements', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='indicatorofcompromise',
            name='severity',
        ),
        migrations.AddField(
            model_name='indicatorofcompromise',
            name='accuracy_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='indicatorofcompromise',
            name='completeness_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='indicatorofcompromise',
            name='composite_trust_score',
            field=models.FloatField(default=0.0, help_text='Weighted evaluation matrix index'),
        ),
        migrations.AddField(
            model_name='indicatorofcompromise',
            name='final_verdict',
            field=models.CharField(default='Suspicious', max_length=50),
        ),
        migrations.AddField(
            model_name='indicatorofcompromise',
            name='freshness_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='indicatorofcompromise',
            name='relevance_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='threatfeed',
            name='historical_accuracy',
            field=models.FloatField(default=0.85, help_text='Base accuracy rating of source (0.0 - 1.0)'),
        ),
        migrations.AlterField(
            model_name='indicatorofcompromise',
            name='ioc_type',
            field=models.CharField(choices=[('ip', 'IP Address'), ('domain', 'Domain Name'), ('hash', 'File Hash (SHA-256)'), ('ttp', 'Tactics & Techniques (TTP)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='indicatorofcompromise',
            name='sources',
            field=models.TextField(help_text='Comma-separated tracking origins'),
        ),
        migrations.AlterField(
            model_name='threatfeed',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='threatfeed',
            name='source_type',
            field=models.CharField(choices=[('url', 'Remote URL'), ('file', 'Manual Upload')], default='url', max_length=10),
        ),
    ]
