# Generated by Django 6.0.6 on 2026-06-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_analystupload_remove_indicatorofcompromise_severity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnalystUpload',
            new_name='UploadArtifact',
        ),
        migrations.DeleteModel(
            name='ThreatFeed',
        ),
        migrations.AlterModelOptions(
            name='indicatorofcompromise',
            options={'ordering': ['-total_mentions', '-confidence']},
        ),
        migrations.AlterModelOptions(
            name='uploadartifact',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RenameField(
            model_name='indicatorofcompromise',
            old_name='last_seen',
            new_name='last_updated',
        ),
        migrations.RemoveField(
            model_name='indicatorofcompromise',
            name='accuracy_score',
        ),
        migrations.RemoveField(
            model_name='indicatorofcompromise',
            name='completeness_score',
        ),
        migrations.RemoveField(
            model_name='indicatorofcompromise',
            name='composite_trust_score',
        ),
        migrations.RemoveField(
            model_name='indicatorofcompromise',
            name='freshness_score',
        ),
        migrations.RemoveField(
            model_name='indicatorofcompromise',
            name='relevance_score',
        ),
        migrations.RemoveField(
            model_name='indicatorofcompromise',
            name='sources',
        ),
        migrations.AddField(
            model_name='indicatorofcompromise',
            name='confidence',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='indicatorofcompromise',
            name='otx_pulses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indicatorofcompromise',
            name='tags',
            field=models.TextField(blank=True, help_text='Comma-separated OTX community tags'),
        ),
        migrations.AlterField(
            model_name='indicatorofcompromise',
            name='final_verdict',
            field=models.CharField(choices=[('Informational', 'Informational'), ('Suspicious', 'Suspicious'), ('High Risk', 'High Risk'), ('Malicious (Critical)', 'Malicious (Critical)')], default='Informational', max_length=50),
        ),
        migrations.AlterField(
            model_name='indicatorofcompromise',
            name='ioc_type',
            field=models.CharField(max_length=50),
        ),
    ]
